language: python
dist: xenial
os: linux
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install: "pip install -r requirements-travis.txt"
script: "py.test tests/test.py"
branches:
  only:
    - master
    - develop
